#pragma once
#include "objects/base/obj.h"
#include <core/aiparam.h>

enum InterfaceEvent
{
    IE_IMP_IM_UI_INVENTORY = 2,
    IE_IMP_IM_UI_MENUBOOK = 3,
    IE_IMP_IM_UI_QUESTLOG = 4,
    IE_IMP_IM_UI_JOURNAL = 5,
    IE_IMP_IM_UI_MAP = 6,
    IE_IMP_IM_UI_VEHICLE_INFO = 7,
    IE_IMP_IM_UI_TOGGLE_INTERFACE = 8,
    IE_IMP_IM_QUICK_SAVE = 9,
    IE_IMP_IM_QUICK_LOAD = 10,
    IE_IMP_IM_RELOAD_WEAPON = 11,
    IE_IMP_IM_UI_BAR = 12,
    IE_IMP_IM_UI_ADDITIONAL_BUILDING = 13,
    IE_IMP_IM_UI_PICKUP_ALL = 14,
    IE_IMP_IM_MODE_GAME_MENU = 15,
    IE_IMP_IM_UI_HELP = 16,
    IE_EV_EV_KEYBINDINGS_CHANGED = 17,
    IE_EV_EV_UI_END_WND_ANIMATION = 18,
    IE_EV_UM_BINDKEYS_DLG = 19,
    IE_EV_UM_BAR = 20,
    IE_EV_UM_WORKSHOP = 21,
    IE_EV_UM_ADMINISTRATION = 22,
    IE_EV_UM_NPC_REPLY_SHOWN = 23,
    IE_EV_UM_SHOP = 24,
    IE_EV_UM_BAR_NPC = 25,
    IE_EV_UM_END_CONVERSATION = 26,
    IE_EV_UM_START_CONVERSATION = 27,
    IE_EV_UM_NAVPOINT_ADDED = 28,
    IE_EV_UM_NAVPOINT_DELETED = 29,
    IE_EV_UM_WEAPONGROUP_CHANGED = 30,
    IE_EV_UM_GADGET_DEACTIVATE = 31,
    IE_EV_UM_VEHICLEPART_DEACTIVATE = 32,
    IE_EV_UM_START_TRADE = 33,
    IE_EV_UM_FINISH_TRADE = 34,
    IE_EV_UM_HIDE_PANEL = 35,
    IE_EV_UM_SHOW_PANEL = 36,
    IE_EV_UM_KNOWN_LEVEL_ADDED = 37,
    IE_EV_UM_LOCAL_MAP = 38,
    IE_EV_UM_GLOBAL_MAP = 39,
    IE_EV_UM_CUR_PROFILE_CHANGED = 40,
    IE_EV_UM_PROFILES_LIST_CHANGED = 41,
    IE_EV_UM_CUR_PROFILE_PARAM_CHANGED = 42,
    IE_EV_UM_SAVEGAME = 43,
    IE_EV_UM_LOADGAME = 44,
    IE_EV_UM_LOAD_LAST_GAME = 45,
    IE_EV_UM_SCREENSHOT_RELEASE = 46,
    IE_EV_UM_SHOW_CURSOR = 47,
    IE_EV_UM_GAME_MODE_CHANGED = 48,
    IE_EV_UM_SHOWGAMEMENU = 49,
    IE_EV_UM_OPTIONS = 50,
    IE_EV_UM_BELONG_MET = 51,
    IE_EV_UM_KNOWN_CLANS_CHANGED = 52,
    IE_EV_UM_GAME_MENU_MODE_ENTER = 53,
    IE_EV_UM_GAME_MENU_MODE_EXIT = 54,
    IE_EV_UM_CHARACTERISTIC_TAB_SEL_CHANGED = 55,
    IE_EV_UM_HELP = 56,
    IE_EV_SM_TOWN = 57,
    IE_EV_SM_REPOSITORY_CHANGED = 58,
    IE_EV_SM_QUEST_WAS_TAKEN = 59,
    IE_EV_SM_QUESTSTATE_CHANGED = 60,
    IE_EV_SM_OBJECT_CREATED = 61,
    IE_EV_SM_OBJECT_DESTROYED = 62,
    IE_EV_SM_OBJECTS_CLEARED = 63,
    IE_EV_SM_PLAYER_VEHICLE_CHANGED = 64,
    IE_EV_SM_VEHICLEPART_CHANGED = 65,
    IE_EV_SM_DYNAMIC_QUEST_CREATED = 66,
    IE_EV_SM_DYNAMIC_QUESTSTATE_CHANGED = 67,
    IE_EV_SM_PLAYER_GOLD_CHANGED = 68,
    IE_EV_SM_GADGET_CHANGED = 69,
    IE_EV_SM_LOCATION_NPC = 70,
    IE_EV_SM_LOCATION_STATE_CHANGED = 71,
    IE_EV_SM_OBJ_MET = 72,
    IE_EV_SM_PROTOTYPE_MET = 73,
    IE_EV_SM_TARGET_CAPTURED = 74,
    IE_EV_SM_PLAYER_MONEY_CHANGED = 75,
    IE_EV_SM_PLAYER_VEHICLE_DAMAGED = 76,
    IE_EV_SM_QUEST_ITEMS_CHANGED = 77,
    IE_EV_SM_TOWN_RUINED = 78,
    IE_EV_SM_FADING_MESSAGE = 79,
    IE_EV_SM_IMPORTANT_FADING_MESSAGE = 80,
    IE_EV_SM_PLAYER_PASS_TO_MAP_FADING = 81,
    IE_EV_SM_NEARBY_CHESTS = 82,
    IE_EV_SM_APPROACH_TOWN = 83,
    IE_CUST_BEFORE_START_LEVEL = 84,
    IE_CUST_START_LEVEL = 85,
    IE_CUST_END_LEVEL = 86,
    IE_CUST_END_LEVEL_BEFORE_CONTINUOUS_LEVEL = 87,
    IE_CUST_SET_PROFILE = 88,
    IE_CUST_NEW_FRAME = 89,
    IE_CUST_NEW_FRAME_FORCE = 90,
    IE_CUST_DD_DRAGITEM_MOVE = 91,
    IE_CUST_DD_START_DRAG = 92,
    IE_CUST_DD_END_DRAG = 93,
    IE_CUST_DD_MOUSE_IN = 94,
    IE_CUST_DD_MOUSE_OUT = 95,
    IE_CUST_DD_DRAGITEM_ACCEPTED = 96,
    IE_CUST_DD_ITEM_WANT_ADD = 97,
    IE_CUST_DD_ITEM_ALLOW_ADD = 98,
    IE_CUST_DD_ITEM_QUICK_DROP = 99,
    IE_CUST_DD_DROP = 100,
    IE_CUST_REPLIES_REINIT = 101,
    IE_CUST_SALETAB_CHANGED = 102,
    IE_CUST_TOWN_NPC = 103,
    IE_CUST_ENTER_BAR = 104,
    IE_CUST_LEAVE_BAR = 105,
    IE_CUST_TOGGLE_FIGNYA = 106,
    IE_CUST_SHOW_VEHICLEPART = 107,
};

namespace ai
{
    struct Event
    {
        /* 0x0000 */ ai::eGameEvent m_eventId;
        /* 0x0004 */ int m_recipientObjId;
        /* 0x0008 */ int m_senderObjId;
        /* 0x000c */ float m_timeOut;
        /* 0x0010 */ int m_framesToPass;
        /* 0x0014 */ float m_timeStamp;
        /* 0x0018 */ int m_debugNum;
        /* 0x001c */ m3d::AIParam m_param1;
        /* 0x0038 */ m3d::AIParam m_param2;
        Event(const ai::Event& __that);
        Event();
        CStr Dump() const;
        void LoadFromXML(m3d::cmn::XmlFile* xmlFile, const m3d::cmn::XmlNode* OwnNode);
        void SaveToXML(m3d::cmn::XmlFile* xmlFile, m3d::cmn::XmlNode* OwnNode) const;
    }; /* size: 0x0054 */

    static_assert(sizeof(ai::Event) == 0x0054);
}
